# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbaea4a8931b0a77db5fea32dd8f9710c240299a38f3c1cffde4d26b00b886bbe0d52dd02e8f209b1c837338a6b00a9302ad8f9a394f9a6246dca30b964907cb

test:
  secret_key_base: d122c89d40fd25731b86e8499fd3cf381b706ac9df6a7610b52ef9853b12dde2887cff68ebf895808666001dca5d375efa7cea5da316bf344770a27cd1a5b739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
